#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright 2015, wywy GmbH
# Author: Christian Becker <christian.becker@wywy.com>
import sys

from check_puppet_agent import MonitoringStatus, main

status = MonitoringStatus()

# this try statement contains all of the code below on purpose
# this is to ensure we have a critical state in the monitoring, in case anything goes wrong in here
# noinspection PyBroadException
try:
    main(status)
# catch all exceptions to create an error in the monitoring in case anything goes wrong in this script
except:
    e = sys.exc_info()
    status.add_status(MonitoringStatus.CRITICAL, str(e[1]))
finally:
    status.exit()
